<?xml version="1.0"?>
<players>
	<sigPlayer>
		<name>Motor Speeds</name>
		<Signal>
			<name>Motor:Speed:RFront</name>
			<color>red</color>
		</Signal>
		<Signal>
			<name>Motor:Speed:LFront</name>
			<color>green</color>
		</Signal>
		<Signal>
			<name>Motor:Speed:LBack</name>
			<color>blue</color>
		</Signal>
		<Signal>
			<name>Motor:Speed:RBack</name>
			<color>orange</color>
		</Signal>
	</sigPlayer>
	<sigPlayer>
		<name>LeftFront Motor</name>
		<Signal>
			<name>Motor:Speed:LFront</name>
			<color>red</color>
		</Signal>
		<Signal>
			<name>MotorCtrl:PWM:LFront</name>
			<color>blue</color>
		</Signal>
		<Signal>
			<name>Motor:Volts:LFront</name>
			<color>green</color>
		</Signal>
		<Signal>
			<name>Motor:Current:LFront</name>
			<color>magenta</color>
		</Signal>
	</sigPlayer>
	<sigPlayer>
		<name>MagMod/Compass Error</name>
		<Signal>
			<name>IMU_ATTI(0):mag:Mod</name>
			<color>black</color>
		</Signal>
		<Signal>
			<name>nonGPSCause</name>
		</Signal>
	</sigPlayer>
	<sigPlayer>
		<name>navHealth</name>
		<signal>
			<name>navHealth</name>
			<color>#ff0000</color>
			<stroke>thick</stroke>
		</signal>
		<signal>
			<name>IMU_ATTI(0):numSats</name>
			<color>#00ff00</color>
			<stroke>thick</stroke>
		</signal>
		<signal>
			<name>flyCState</name>
		</signal>
	</sigPlayer>
	<geoPlayer>
		<geopath>
			<name>IMU0</name>
			<symbol>I0</symbol>
			<Latitude>IMU_ATTI(0):Latitude</Latitude>
			<Longitude>IMU_ATTI(0):Longitude</Longitude>
			<Altitude>IMU_ATTI(0):relativeHeight:C</Altitude>
			<headingSignal>IMU_ATTI(0):yaw:C</headingSignal>
			<headingSignal>IMU_ATTI(0):magYaw:C</headingSignal>
			<headingSignal>IMU_ATTI(0):tiltDirectionEarthFrame:C</headingSignal>
			<headingSignal>AirSpeed:windDirection</headingSignal>
		</geopath>
		<geopath>
			<name>IMU1</name>
			<symbol>I1</symbol>
			<default>dontDisplay</default>
			<Latitude>IMU_ATTI(1):Latitude</Latitude>
			<Longitude>IMU_ATTI(1):Longitude</Longitude>
			<Altitude>IMU_ATTI(1):relativeHeight:C</Altitude>
			<headingSignal>IMU_ATTI(1):yaw:C</headingSignal>
			<headingSignal>IMU_ATTI(1):tiltDirectionEarthFrame:C</headingSignal>
			<headingSignal>IMU_ATTI(1):magYaw:C</headingSignal>
		</geopath>
		<geopath>
			<name>IMUCalcs(0)</name>
			<default>dontDisplay</default>
			<symbol>IC0</symbol>
			<Latitude>IMUCalcs(0):Lat:C</Latitude>
			<Longitude>IMUCalcs(0):Long:C</Longitude>
			<headingSignal>IMU_ATTI(0):yaw:C</headingSignal>
		</geopath>
		<geopath>
			<name>IMUCalcs(1)</name>
			<default>dontDisplay</default>
			<symbol>IC1</symbol>
			<Latitude>IMUCalcs(1):Lat:C</Latitude>
			<Longitude>IMUCalcs(1):Long:C</Longitude>
			<headingSignal>IMU_ATTI(1):yaw:C</headingSignal>
		</geopath>
		<geopath>
			<name>GPS</name>
			<default>dontDisplay</default>
			<symbol>G</symbol>
			<Latitude>GPS:Lat</Latitude>
			<Longitude>GPS:Long</Longitude>
		</geopath>

		<geoPath>
			<name>Home</name>
			<symbol>H</symbol>
			<Latitude>HP:Latitude</Latitude>
			<Longitude>HP:Longitude</Longitude>
		</geoPath>

		<geopath>
			<name>AdsbEscape</name>
			<default>dontDisplay</default>
			<symbol>Adsb</symbol>
			<Latitude>AdsbEscape:latitude</Latitude>
			<Longitude>AdsbEscape:longitude</Longitude>
			<headingSignal>AdsbEscape:heading</headingSignal>
		</geopath>
	</geoPlayer>
</players>
