<?xml version="1.0"?>
<players>
	<sigPlayer>
		<name>Motor Speeds</name>
		<Signal>
			<name>Motor:Speed:RFront</name>
			<color>red</color>
		</Signal>
		<Signal>
			<name>Motor:Speed:LFront</name>
			<color>green</color>
		</Signal>
		<Signal>
			<name>Motor:Speed:LBack</name>
			<color>blue</color>
		</Signal>
		<Signal>
			<name>Motor:Speed:RBack</name>
			<color>orange</color>
		</Signal>
	</sigPlayer>
	<sigPlayer>
		<name>LeftFront Motor</name>
		<Signal>
			<name>Motor:Speed:LFront</name>
			<color>red</color>
		</Signal>
		<Signal>
			<name>Motor:PWM:LFront</name>
			<color>blue</color>
		</Signal>
		<Signal>
			<name>Motor:Volts:LFront</name>
			<color>green</color>
		</Signal>
		<Signal>
			<name>Motor:PPM:LFront</name>
			<color>black</color>
		</Signal>
		<Signal>
			<name>Motor:Current:LFront</name>
			<color>magenta</color>
		</Signal>
	</sigPlayer>

	<sigPlayer>
		<name>MagMod/Compass Error</name>
		<Signal>
			<name>Mag:Mod</name>
			<color>black</color>
		</Signal>
		<Signal>
			<name>nonGPSCause</name>
		</Signal>
	</sigPlayer>
	<sigPlayer>
		<name>Satellites-GPSHealth</name>
		<signal>
			<name>numSats</name>
			<color>#ff0000</color>
			<stroke>thick</stroke>
		</signal>
		<signal>
			<name>gpsHealth</name>
			<color>#00ff00</color>
			<stroke>thick</stroke>
		</signal>
	</sigPlayer>
	<geoPlayer>
	<geopath>
			<name>AC0</name>
			<symbol>A0</symbol>
			<Latitude>IMU_ATTI(0):Latitude</Latitude>
			<Longitude>IMU_ATTI(0):Longitude</Longitude>
			<Altitude>General:relativeHeight</Altitude>
			<headingSignal>IMU_ATTI(0):yaw</headingSignal>
			<headingSignal>IMU_ATTI(0):magYaw</headingSignal>
		</geopath>
		<geopath>
			<name>AC1</name>
			<symbol>A1</symbol>
			<Latitude>IMU_ATTI(1):Latitude</Latitude>
			<Longitude>IMU_ATTI(1):Longitude</Longitude>
			<Altitude>General:relativeHeight</Altitude>
			<headingSignal>IMU_ATTI(1):yaw</headingSignal>
			<headingSignal>IMU_ATTI(1):magYaw</headingSignal>
		</geopath>
		<geopath>
			<name>AC</name>
			<symbol>A</symbol>
			<Latitude>Latitude</Latitude>
			<Longitude>Longitude</Longitude>
			<Altitude>relativeHeight</Altitude>
			<headingSignal>Yaw</headingSignal>
			<headingSignal>magYaw</headingSignal>
			<headingSignal>Motor:thrustAngle</headingSignal>
		</geopath>
		<geopath>
			<name>ImuCalcs</name>
			<Latitude>ImuCalcs(0):Lat</Latitude>
			<Longitude>ImuCalcs(0):Long</Longitude>
			<headingSignal>Yaw</headingSignal>
		</geopath>
		<geoPath>
			<name>Home</name>
			<symbol>H</symbol>
			<Latitude>HP:Latitude</Latitude>
			<Longitude>HP:Longitude</Longitude>
		</geoPath>
		<geopath>
			<name>Tablet/RC</name>
			<symbol>T</symbol>
			<Latitude>Tablet:Latitude</Latitude>
			<Longitude>Tablet:Longitude</Longitude>
		</geopath>

	</geoPlayer>
</players>
